# Generated by Django 3.1.4 on 2021-01-05 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(max_length=10),
        ),
    ]
