# Generated by Django 3.1.4 on 2021-01-05 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ap', '0002_auto_20210105_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_on',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_on',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
