# Generated by Django 3.1.4 on 2021-01-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ap', '0004_auto_20210105_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
    ]
