# Generated by Django 3.1.4 on 2021-01-06 06:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ap', '0005_auto_20210106_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
